spark-master:
  ports:
  - 6066:6066/tcp
  - 7077:7077/tcp
  - 8080:8080/tcp
  - 4040:4040/tcp
  log_driver: ''
  labels:
    io.rancher.scheduler.affinity:host_label: spark-master=1
  tty: true
  command:
  - /spark/mkzbin/start.sh
  - master
  log_opt: {}
  image: makazi/rancher-spark-standalone:1.6.2-hadoop2.4
  stdin_open: true
spark-slaves:
  ports:
  - 8888:8888/tcp
  - 8081:8081/tcp
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label_ne: spark-master=1
  tty: true
  command:
  - /spark/mkzbin/start.sh
  - slave
  - spark://spark-master:7077
  log_opt: {}
  image: makazi/rancher-spark-standalone:1.6.2-hadoop2.4
  links:
  - spark-master:spark-master
  stdin_open: true
